/**
 * Prisma Enum Types
 * 
 * Prisma 클라이언트가 생성되지 않은 경우를 대비해 직접 정의
 * schema.prisma의 enum 정의와 일치해야 함
 */

export enum SessionEndStatus {
  SUCCESS_CONFIRMED = 'SUCCESS_CONFIRMED',
  LOW_CONFIDENCE = 'LOW_CONFIDENCE',
  FAILED_AFTER_QUESTIONS = 'FAILED_AFTER_QUESTIONS',
  SUBMITTED_HINT = 'SUBMITTED_HINT',
}

export enum TagType {
  GENRE_PRIMARY = 'GENRE_PRIMARY',
  GENRE_SECONDARY = 'GENRE_SECONDARY',
  GENRE_SUBGENRE = 'GENRE_SUBGENRE',
  MOOD = 'MOOD',
  OBJECT = 'OBJECT',
  NARRATIVE_HINT = 'NARRATIVE_HINT',
  COUNTRY = 'COUNTRY',
  YEAR = 'YEAR',
}

export enum ConfidenceLevel {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum ShareType {
  OG_IMAGE = 'OG_IMAGE',
  TWITTER_CARD = 'TWITTER_CARD',
  FACEBOOK_SHARE = 'FACEBOOK_SHARE',
  CACHE_RESPONSE = 'CACHE_RESPONSE',
  CDN_PATH = 'CDN_PATH',
}

export enum PIIDataType {
  USER_MEMORY_SENTENCE = 'USER_MEMORY_SENTENCE',
  SEARCH_SESSION = 'SEARCH_SESSION',
  FEEDBACK = 'FEEDBACK',
  USER_PROFILE = 'USER_PROFILE',
}

export enum QuestionType {
  GENRE_CLARIFICATION = 'GENRE_CLARIFICATION',
  MOOD_CLARIFICATION = 'MOOD_CLARIFICATION',
  OBJECT_CLARIFICATION = 'OBJECT_CLARIFICATION',
  YEAR_CLARIFICATION = 'YEAR_CLARIFICATION',
  OTHER = 'OTHER',
}

export enum FeedbackType {
  CONFIRMED = 'CONFIRMED',
  NOT_FOUND = 'NOT_FOUND',
  SUBMITTED_HINT = 'SUBMITTED_HINT',
  LOW_CONFIDENCE = 'LOW_CONFIDENCE',
}

export enum FailureType {
  NO_CANDIDATES = 'NO_CANDIDATES',
  LOW_CONFIDENCE_ALL = 'LOW_CONFIDENCE_ALL',
  USER_REJECTED_ALL = 'USER_REJECTED_ALL',
  QUESTION_FAILED = 'QUESTION_FAILED',
  TIMEOUT = 'TIMEOUT',
  API_ERROR = 'API_ERROR',
}

export enum APIModule {
  GENRE_CLASSIFIER = 'GENRE_CLASSIFIER',
  CANDIDATE_RANKER = 'CANDIDATE_RANKER',
  QUESTION_SELECTOR = 'QUESTION_SELECTOR',
  FEEDBACK_HANDLER = 'FEEDBACK_HANDLER',
}

